spring:
  application:
    name: email-service

  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 199907

  redis:
    host: 175.24.77.8
    port: 6379
    password:
    timeout:

  rabbitmq:
    host: 175.24.77.8
    port: 5672
    username: zj
    password: root
    virtual-host: demo

  mail:
    host: smtp.qq.com
    username: 2505560247@qq.com
    password: waimfbwecwijebeg
    default-encoding: utf-8

server:
  port: 9089

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/

activeAccountServer: http://localhost:9089/email/active?=uuid