spring:
  application:
    name: email-regist-web

  redis:
    host: 175.24.77.8
    port: 6379
    password:
    timeout:

  rabbitmq:
    host: 175.24.77.8
    port: 5672
    username: zj
    password: root
    virtual-host: demo

server:
  port: 8089



eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/
