
spring:
  application:
    name: shop-product-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///qf-v6?serverTimezone=UTC
      username: root
      password: 123
  redis:
      host: 175.24.77.8
      port: 6379
      jedis:
        pool:
          max-active: 20

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/



