spring:
  application:
    name: shop-order
  redis:
    host: 175.24.77.8
    port: 6379
    jedis:
      pool:
        max-active: 20
  rabbitmq:
      host: 175.24.77.8
      port: 5672
      username: zj
      password: root
      virtual-host: demo

server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/

