spring:
  application:
    name: shop-sso

  redis:
    host: 175.24.77.8
    port: 6379
    password:
    timeout:
    jedis:
      pool:
        max-active: 20

server:
  port: 8090


eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/
