spring:
  application:
    name: shop-pay-service
  redis:
    host: 175.24.77.8
    port: 6379
    jedis:
      pool:
        max-active: 20
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/
