
spring:
  application:
    name: shop-product-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///qf-v6?serverTimezone=UTC
      username: root
      password: 123

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/



