
spring:
  application:
    name: shop-search-service

  data:
      solr:
        host: http://175.24.77.8:8983/solr/ik_core

  datasource:
      url: jdbc:mysql://localhost:3306/qf-v6?serverTimezone=UTC
      username: root
      password: 123

  rabbitmq:
      host: 175.24.77.8
      port: 5672
      username: zj
      password: root
      virtual-host: demo


server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/
