spring:
  application:
    name: shop-phoneregister-server

  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 199907

  redis:
    host: 175.24.77.8
    port: 6379
    password:
    timeout:

  rabbitmq:
    host: 175.24.77.8
    port: 5672
    username: zj
    password: root
    virtual-host: demo

server:
  port: 9088

sms:
  Url: http://106.ihuyi.cn/webservice/sms.php?method=Submit
  account: C32284572
  password: 55c71d13888f723101291d8d0c6ada21
  mobile: 19918805818

eureka:
  client:
    serviceUrl:
      defaultZone: http://175.24.77.8:8761/eureka/